#!/usr/bin/env bash
# A Bash Script that transfers a file from our clinet to a server

if [ "$#" -eq 0 ]; then 
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi

FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
SSH_KEY_PATH=$4

scp -o "StrictHostKeyChecking=no" -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/
