#!/usr/bin/env bash
# Install nginx web server

# update packages
sudo apt-get -y update

# install nginx web server
apt-get -y install nginx

# append custom text to nginx html index page
echo "Hello World!" > /var/www/html/index.html

# restarting nginx web server
sudo /etc/init.d/nginx restart
