#!/usr/bin/env bash
# This scripts prints fizz buzz fizzbuzz depends on modulo of a number 

# shellcheck disable=SC2034


for i in {0..100}; do

if ((i % 3 == 0 && i % 5 == 0)); then
	echo "FizzBuzz"
elif ((i % 3 == 0 )); then
	echo "Fizz"
elif ((i % 5 == 0)); then
	echo "Buzz"
else
	echo "$i"
fi
done
