#!/usr/bin/env bash
# This script displays "Best School" 10 times 

counter=1

while [ $counter -lt 11 ]; do
if [ $counter == 9 ]; then
	echo "hi"
else
	echo "Best School"
fi
   ((counter=counter+1))
done
