#!/usr/bin/env bash
# This script displays "Best School" 10 times 

counter=0

while [ $counter -lt 10 ]; do
if [ $counter == 9 ]; then
	echo "Hi"
else
	echo "Best School"
fi
   ((counter=counter+1))
done

echo "Best School"
